### ISSUE TITLE
Arrays of enums

### ISSUE THREAD

**Issue by TheFlow95** [MaxDesiatov/XMLCoder#91] opened 2019-04-25 04:07 UTC
I am trying to decode this XML:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<container>
    <p>
        <run>
            <id>1518</id>
            <text>I am answering it again.</text>
        </run>
        <properties>
            <id>431</id>
            <title>A Word About Wake Times&#xD;</title>
        </properties>
        <br />
    </p>
    <p>
        <run>
            <id>1519</id>
            <text>I am answering it again.</text>
        </run>
    </p>
</container>
```

This is my implementation:
```swift
struct Run: Decodable {
    let id: Int
    let text: String
}

struct Properties: Decodable {
    let id: Int
    let title: String
}

struct Break: Decodable {
    
}

enum Entry: Decodable {
    case run(Run)
    case properties(Properties)
    case br(Break)
    
    private enum CodingKeys: String, CodingKey {
        case run, properties, br
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        do {
            self = .run(try container.decode(Run.self, forKey: .run))
        } catch DecodingError.keyNotFound {
            do {
                self = .properties(try container.decode(Properties.self, forKey: .properties))
            } catch DecodingError.keyNotFound {
                self = .br(try container.decode(Break.self, forKey: .br))
            }
        }
    }
}

struct Paragraph: Decodable {
    let entries: [Entry]
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        entries = try container.decode([Entry].self)
    }
}

do {
    let result = try XMLDecoder().decode([Paragraph].self, from: data)
    for paragraph in result {
        print("Paragraph :")
        for entry in paragraph.entries {
            switch entry {
            case .run(let run):
                print("Run : \(run)")
            case .properties(let properties):
                print("Properties : \(properties)")
            case .br(let br):
                print("Break : \(br)")
            }
        }
        print("End paragraph")
    }
}
catch {
    print(error)
}
```

But I am getting an odd `DecodingError.keyNotFound`…

I know that there is already an issue about enums but I think this one is different because I am trying to do an array of array of enums and I don't get the same error.

I am using an enum because I want to be able to decode a `<p>` with different optional elements and keep the order in which they are.

Can you tell me if this is a bug from the library or from my own code? Can achieve what I want to do by some other way?

Thank you!

**Comment by MaxDesiatov** [comment] 2019-04-28 19:06
Hi @TheFlow95, thank you for providing the snippets. There's an additional issue here caused by a missing struct that reflects the XML:

```swift
struct Container: Decodable {
    let paragraphs: [Paragraph]

    enum CodingKeys: String, CodingKey {
        case paragraphs = "p"
    }
}
``` 

After adding it and decoding into `Container.self` instead of `[Paragraph].self` there are no more errors thrown. The other problem though is that `Entry.init(from:)` uses a keyed container, but reads only a single key from it. This means that only a single `Entry` is decoded into a property of `Paragraph`. I'm currently looking for a best way to solve this, will keep you updated. Thanks!

**Comment by TheFlow95** [comment] 2019-04-29 01:50
Thanks for your answer, I'm looking forward to have a fix for this!

**Comment by TheFlow95** [comment] 2019-04-29 02:52
By playing with the library, I ran into another bug related to this one. When trying to decoding the following XML with the same code as before:
```xml
<?xml version="1.0" encoding="UTF-8"?>
 <container>
    <p>
        <run>
            <id>1518</id>
            <text>I am answering it again.</text>
        </run>
        <properties>
            <id>431</id>
            <title>A Word About Wake Times&#xD;</title>
        </properties>
        <br/>
        <run>
            <id>1519</id>
            <text>Hello!</text>
        </run>
    </p>
    <p>
        <run>
            <id>1520</id>
            <text>I am answering it again.</text>
        </run>
    </p>
</container>
```
I get the following error:
>typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "p", intValue: nil), XMLKey(stringValue: "0", intValue: 0), XMLKey(stringValue: "0", intValue: 0), XMLKey(stringValue: "0", intValue: 0), XMLKey(stringValue: "0", intValue: 0), CodingKeys(stringValue: "run", intValue: nil)], debugDescription: "Expected to decode Dictionary<String, Any> but found SharedBox<UnkeyedBox> instead.", underlyingError: nil))

I think that the error is because I have two `run` elements into the first `p` but I thought that it would handle it. Can you help?

**Comment by MaxDesiatov** [comment] 2019-04-30 14:49
After spending some time on this I think that using `singleValueContainer` for `Paragraph` here wouldn't work. We need to preserve the order and duplicate keys in the container, so the best fit would be to rely on the standard unkeyed container in the compiler-generated `init(from: Decoder)` for `Paragraph`. On the other hand, `Entry` should be able to read the name of the tag to determine the actual enum value in its own `init(from: Decoder)`. 

This means we need to pass through the tag name into the keyed container somehow and we can't get the element name from the key in the parent `Paragraph.init(from: Decoder)` as we're required to use an unkeyed container there. Seems like `Decodable/Encodable` is a good fit for simpler formats like JSON, but can't express all these nuances of XML directly. This is similar to a problem we had previously with element values, which was resolved by introducing [the value intrinsic](https://github.com/MaxDesiatov/XMLCoder#coding-key-value-intrinsic).

Based on this, I'm thinking of adding a new intrinsic, potentially called `xmlElementName`. According to the XML spec, element and attribute names can't start with `xml` string, so users are very unlikely to need that name used for a real element or an attribute. During decoding you'd be able to get the element name via that key and initialize a proper enum case in `Entry.init(from: Decoder)`. I'm open to considering other options and names for the intrinsic. Thanks!

**Comment by TheFlow95** [comment] 2019-05-02 01:30
Sounds good to me!

**Closed** 2019-07-30 18:39 UTC
